# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :postfix => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.102',
  },
  
  :mailclient => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.103',
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048","--cpus", "4"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "postfix"
        box.vm.provision "shell", run: "always", inline: <<-SHELL		  
		  sudo systemctl stop firewalld
		  setenforce 0
          yum install epel-release wget -y
		  yum install postfix -y
		  alternatives --set mta /usr/sbin//root/sendmail.postfix
		  yum install dovecot -y
		  yum install telnet mutt nc -y
		  mkdir /var/mail/mydomain
		  useradd postfixtester
		  echo -n "RooTqwerty123\nRooTqwerty123" | passwd postfixtester
		  mv /etc/postfix/main.cf /etc/postfix/main.cf.bak
		  cp /vagrant/postfix/main.cf /etc/postfix/main.cf
		  mv /etc/dovecot/dovecot.conf /etc/dovecot/dovecot.conf.bak
		  cp /vagrant/dovecot/dovecot.conf.work /etc/dovecot/dovecot.conf
		  cp /vagrant/imap /etc/pam.d/imap
		  cp -f /vagrant/dovecot-pam /etc/pam.d/dovecot
		  cp /vagrant/server.muttrc /root/.muttrc
  		  systemctl start postfix
		  systemctl start dovecot
		  echo "ehlo localhost" > /root/send
		  echo "mail from:admin@test.local" >> /root/send
		  echo "rcpt to:<postfixtester>" >> /root/send
		  echo "data" >> /root/send
		  echo "test admin mail" >> /root/send
		  echo "." >> /root/send
		  echo "quit" >> /root/send
		  #cat /root/send | nc localhost 25

          SHELL
		  
      when "mailclient"
        box.vm.provision "shell", run: "always", inline: <<-SHELL		  
		  sudo systemctl stop firewalld
		  setenforce 0
          yum install epel-release wget -y
		  yum install telnet mutt nc -y
		  cp /vagrant/client.muttrc /root/.muttrc
		  echo "ehlo 192.168.11.102" > /root/send
		  echo "mail from:admin@test.local" >> /root/send
		  echo "rcpt to:<postfixtester>" >> /root/send
		  echo "data" >> /root/send
		  echo "test admin mail" >> /root/send
		  echo "." >> /root/send
		  echo "quit" >> /root/send
		  cat /root/send | nc 192.168.11.102 25


          SHELL
		  

      end

      end
   end
end
