---
 - hosts: backup
   become: true
   tasks:
   - include_role:
        name: backup
     vars:
       primary: nginx1
       secondary:
        - nginx2
       glustervolname: volume1
       glustermountdir: /glusterfs
       mntpermissions: '0755'
       glustersigpackage: centos-release-gluster7
       backup_dir: /backup
       backup_target: /glusterfs
       BORG_PASSPHRASE: password
       PGPASSWORD: postgrespassword
       postgres_host: 192.168.11.121
       postgres_port: 5000
       postgres_db: nextcloud
       postgres_user: postgres
       postgres_dest: /dbbackup


