---
 - hosts: web
   become: true
   tasks:
   - include_role:
        name: glusterfs
     vars:
       primary: nginx1
       secondary:
        - nginx2
       glusterdir: /glusterfs_data
       permissions: '0755'
       glustervolname: volume1
       replicacount: 2
       glustermountdir: /glusterfs
       mntpermissions: '0755'
       glustersigpackage: centos-release-gluster7


