[proxy]
proxy1 ansible_user=root priority=102
proxy2 ansible_user=root priority=100

[web]
nginx1 ansible_user=root role=master
nginx2 ansible_user=root role=secondary

[haproxy]
haproxy1 ansible_user=root priority=102
haproxy2 ansible_user=root priority=100

[patroni]
patroni1 ansible_user=root int=192.168.11.108 ETCD_NAME=patroni1 first=yes
patroni2 ansible_user=root int=192.168.11.109 ETCD_NAME=patroni2
patroni3 ansible_user=root int=192.168.11.110 ETCD_NAME=patroni3

[createdb]
patroni1 ansible_user=root
patroni2 ansible_user=root
patroni3 ansible_user=root

[log]
log ansible_user=root

[log-clients]
patroni1 ansible_user=root
patroni2 ansible_user=root
patroni3 ansible_user=root
proxy1 ansible_user=root 
proxy2 ansible_user=root 
nginx1 ansible_user=root 
nginx2 ansible_user=root 
haproxy1 ansible_user=root 
haproxy2 ansible_user=root 

[proxy:vars]
port=80
upstreamname=myapp
method=ip_hash
server_name=example.com
backends=["server1", "server2","server3"]