[proxy]
proxy1 ansible_user=root priority=102
proxy2 ansible_user=root priority=100

[web]
nginx1 ansible_user=root role=master
nginx2 ansible_user=root role=secondary

[proxy:vars]
port=80
upstreamname=myapp
method=ip_hash
server_name=example.com
backends=["server1", "server2","server3"]