---
 - hosts: proxy
   become: true
   tasks:
   - include_role:
        name: keepalived
     vars:
       interface: enp0s8
       virtual_router_id: 55
       #priority: "{{ priority }}"
       advert_int: 1
       auth_type: PASS
       auth_pass: Secret
       virtual_ipaddress: 192.168.11.120/24
