---
 - hosts: web
   become: true
   tasks:
   - import_role:
        name: nextcloud-nginx          
     vars:
       nextcloud_url: nextcloud-18.0.3.zip
       port: 80
       server_name: example.com
       root: /var/www/nextcloud
       datacloud: /glusterfs/data
       data_dir_in_config: /var/www/nextcloud/data
       dbtype: pgsql
       dbhost: 192.168.11.121:5000
       dbname: nextcloud
       dbuser: nextcloud
       dbpassword: nextcloudpass
       nextcloud_user: admin
       nextcloud_user_pass: admin

