---
 - hosts: proxy
   become: true
   tasks:
   - include_role:
        name: nginx-proxy
     vars:
       port: 80
       upstreamname: myapp
       method: ip_hash
       server_name: example.com
       location: /
       fail_timeout: 2s
       max_fails: 1
       weight: 5
       backends:
        - nginx1
        - nginx2
       proxy_set_headers: 
        - Host $host
        - X-Real-IP $remote_addr
        - X-Forwarded-For $proxy_add_x_forwarded_for
