---
 - hosts: web
   become: true
   tasks:
   - include_role:
        name: nginx-php
     vars:
       port: 80
       server_name: example.com
       root: /var/www/laravel/public
       max_fails: 1
       weight: 5
       backends:
        - nginx1
        - nginx2
