Vagrant.configure('2') do |config|
    config.vm.box = "centos/7"
    config.vm.define "kernel_from_repo"
    config.vm.provider :virtualbox do |vb|
        vb.name = "kernel_from_repo"
	vb.cpus = "2"
	vb.memory = "2048"
    end
end
