Vagrant.configure('2') do |config|
    config.vm.box = "centos/7"
    config.vm.define "clean_Centos"
    config.vm.provider :virtualbox do |vb|
        vb.name = "clean_Centos"
	vb.cpus = "2"
	vb.memory = "2048"
    end
end
