---
    - name: nginx start
      service: name=nginx state=started

    - name: nginx restart
      service: name=nginx state=restarted
      
    - name: uwsgi start
      service: name=uwsgi state=started