---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  - name: Create group ops with gid 1234
    ipagroup:
      ipaadmin_password: MyPassword123
      name: ops
      gidnumber: 1234

  - name: Create group sysops
    ipagroup:
      ipaadmin_password: MyPassword123
      name: sysops
      user:
      - pinky

  - name: Create group appops
    ipagroup:
      ipaadmin_password: MyPassword123
      name: appops

