---      
    
    - name: Install keepalived
      yum: pkg=keepalived state=latest
      notify:
          - keepalived start
          
    - name: Enable keepalived  Service
      service:
        name: keepalived 
        enabled: yes
        state: started

    
    - name: Enable vrrp firewall rule
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled  

    - name: Add keepalived cofig
      template: src=keepalived.conf dest=/etc/keepalived/keepalived.conf

    - name: restart keepalived  Service
      service:
        name: keepalived 
        enabled: yes
        state: restarted



