---      
    
    - name: Install keepalived
      yum: pkg=keepalived state=latest
          
    - name: Enable keepalived  Service
      service:
        name: keepalived 
        enabled: yes

    - name: Start keepalived  Service
      service:
        name: keepalived 
        state: started

    
    - name: Add keepalived cofig
      template: src=keepalived.conf dest=/etc/keepalived/keepalived.conf

    - name: Restart keepalived  Service
      service:
        name: keepalived 
        state: restarted



