---
- name: Playbook to manage sudo command
  hosts: ipaserver
  become: true

  tasks:
  # Ensure sudo command is absent
  - ipasudocmd:
      ipaadmin_password: MyPassword123
      name: /usr/bin/su
      state: absent
