---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - ipavault:
      ipaadmin_password: MyPassword123
      name: stdvault
      vault_type: standard
      username: admin
      description: A standard private vault.
