# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :mysql1 => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.102',
  },
  
  :mysql2 => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.103',
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048","--cpus", "4"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "mysql1"
        box.vm.provision "shell", run: "always", inline: <<-SHELL		  
		  sudo systemctl stop firewalld
		  setenforce 0
          yum install epel-release wget -y
		  wget https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm && rpm -Uvh mysql80-community-release-el7-1.noarch.rpm
		  yum install mysql-server -y
		  systemctl start mysqld
		  systemctl enable mysqld
		  systemctl status mysqld
		  mv /etc/my.cnf /etc/my.cnf.old
		  cp /vagrant/my.cnf.mysql1 /etc/my.cnf 
		  systemctl restart mysqld
		  sleep 30
		  systemctl status mysqld
		  mysql -u root --password="$(cat /var/log/mysqld.log | grep password | awk {'print $13'})" --connect-expired-password --execute=" ALTER USER 'root'@'localhost' IDENTIFIED BY 'Mysql77RooTP@S$';"
   		  mysql -u root --password='Mysql77RooTP@S$' --execute='show master status ;'
		  mysql -u root --password='Mysql77RooTP@S$' --execute='create database bet ;'
		  mysql -u root --password='Mysql77RooTP@S$' bet < /vagrant/bet-4560-4974c3.dmp
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute='show tables;'
		  mysql -u root --password='Mysql77RooTP@S$' --execute="create user 'repl_user'@'%' identified by 'Mysql77RepLP@S$';"
 		  mysql -u root --password='Mysql77RooTP@S$' --execute="ALTER USER 'repl_user'@'%' IDENTIFIED WITH mysql_native_password BY 'Mysql77RepLP@S$';"
		  mysql -u root --password='Mysql77RooTP@S$' --execute="GRANT EVENT ON *.* TO 'repl_user'@'%';"
		  mysql -u root --password='Mysql77RooTP@S$' --execute="GRANT REPLICATION SLAVE ON *.* TO 'repl_user'@'%';"
		  mysql -u root --password='Mysql77RooTP@S$' --execute="show master status ;"
		  mysqldump --all-databases -flush-privileges --single-transaction --flush-logs --triggers --routines --events --hex-blob -u root --password='Mysql77RooTP@S$'  > /vagrant/mysqlbackup_dump.sql
		  head -n30 /vagrant/mysqlbackup_dump.sql
 		  mysql -u root --password='Mysql77RooTP@S$' bet --execute="select * from bookmaker ;"
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute="INSERT INTO bookmaker (id,bookmaker_name) VALUES(15,'otus');"
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute="select * from bookmaker ;"

          SHELL
		  
      when "mysql2"
        box.vm.provision "shell", run: "always", inline: <<-SHELL		  
		  sudo systemctl stop firewalld
		  setenforce 0
          yum install epel-release wget -y
		  wget https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm && rpm -Uvh mysql80-community-release-el7-1.noarch.rpm
		  yum install mysql-server -y
		  systemctl start mysqld
		  systemctl enable mysqld
		  systemctl status mysqld
		  mv /etc/my.cnf /etc/my.cnf.old
		  cp /vagrant/my.cnf.mysql2 /etc/my.cnf 
		  systemctl restart mysqld
		  sleep 30
		  systemctl status mysqld
		  mysql -u root --password="$(cat /var/log/mysqld.log | grep password | awk {'print $13'})" --connect-expired-password --execute=" ALTER USER 'root'@'localhost' IDENTIFIED BY 'Mysql77RooTP@S$';"
		  mysql -u root --password='Mysql77RooTP@S$' --execute='show master status ;'
		  mysql -u root --password='Mysql77RooTP@S$' --execute="show global variables like 'gtid_executed';"
		  mysql -u root --password='Mysql77RooTP@S$'  < /vagrant/mysqlbackup_dump.sql
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute='show tables;'
		  mysql -u root --password='Mysql77RooTP@S$' --execute="CHANGE MASTER TO MASTER_HOST = '192.168.11.102', MASTER_PORT = 3306, MASTER_USER = 'repl_user', MASTER_PASSWORD = 'Mysql77RepLP@S$', MASTER_AUTO_POSITION = 1;"
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute='start slave;'
		  sleep 30
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute='show slave status \G'
		  mysql -u root --password='Mysql77RooTP@S$' bet --execute="select * from bookmaker ;"

          SHELL
		  

      end

      end
   end
end
