# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :bacula => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.102',
  },
  :client => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.101',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "4096"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "client"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQulD+SK4ggadzuJZdksaB7VVAXzDbeYHkd41savMnzxLiVXW4SFUXlBx4c1B8J4thzlgH/dXiDKgyPsjPPiHJaao446jJrJxBT/VATUg+MEYY48qUifCg9cTffAis512MhyvCGInfU2B/FMCz8zF9P0sDp+NoHWOCamawJ+B2Sk3r9VgtS30l34WTDBINbcqtlEq1IKTWHHLuDw84bRLHBF4x8bn6REYjb+UF98zHlhV539iikHjZSqQa1KHnp+1Ew9IY1WoUDukjwuAa6YGkWjO1ughAlZ4xpzgp1coOp+C0tTTI4V45soO2V2fG1xXIBqGteYv/oBDDZfQ6kj3z" >> /home/vagrant/.ssh/authorized_keys		
		  mkdir /root/.ssh/
		  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQulD+SK4ggadzuJZdksaB7VVAXzDbeYHkd41savMnzxLiVXW4SFUXlBx4c1B8J4thzlgH/dXiDKgyPsjPPiHJaao446jJrJxBT/VATUg+MEYY48qUifCg9cTffAis512MhyvCGInfU2B/FMCz8zF9P0sDp+NoHWOCamawJ+B2Sk3r9VgtS30l34WTDBINbcqtlEq1IKTWHHLuDw84bRLHBF4x8bn6REYjb+UF98zHlhV539iikHjZSqQa1KHnp+1Ew9IY1WoUDukjwuAa6YGkWjO1ughAlZ4xpzgp1coOp+C0tTTI4V45soO2V2fG1xXIBqGteYv/oBDDZfQ6kj3z" >> /root/.ssh/authorized_keys
		  sudo systemctl stop firewalld
		  echo "192.168.11.101  bacula" >> /etc/hosts
		  yum install epel-release -y
		  yum install -y bacula-client
          SHELL
		  
      when "bacula"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install epel-release -y
		  yum install -y bacula-director bacula-storage bacula-console bacula-client mariadb-server
          cp /vagrant/id_rsa /home/vagrant/.ssh/
		  cp /vagrant/id_rsa /root/.ssh/
		  chmod 0600 /root/.ssh/id_rsa
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
          chmod 0600 /home/vagrant/.ssh/id_rsa
          echo "192.168.11.102  client" >> /etc/hosts
		  export ANSIBLE_HOST_KEY_CHECKING=false
		  ssh-keyscan -H web >> ~/.ssh/known_hosts
		  systemctl start mariadb
		  systemctl enable mariadb
		  /usr/libexec/bacula/grant_mysql_privileges
		  /usr/libexec/bacula/create_mysql_database -u root
		  /usr/libexec/bacula/make_mysql_tables -u bacula
		  mysql -u root -e 'UPDATE mysql.user SET Password=PASSWORD("bacula_db_password") WHERE User="bacula";'
		  mysql -u root -e 'FLUSH PRIVILEGES;'
		  echo 1 | alternatives --config libbaccats.so
		  mkdir -p /bacula/backup /bacula/restore
		  chown -R bacula:bacula /bacula
		  chmod -R 700 /bacula
		  cp -f /vagrant/bacula-dir.conf /etc/bacula/bacula-dir.conf 
		  cp -f /vagrant/bacula-sd.conf /etc/bacula/bacula-sd.conf 
		  bacula-sd -tc /etc/bacula/bacula-dir.conf 
		  bacula-sd -tc /etc/bacula/bacula-sd.conf
		  systemctl start bacula-dir
		  systemctl start bacula-sd
		  systemctl start bacula-fd
		  systemctl enable bacula-dir
		  systemctl enable bacula-sd
		  systemctl enable bacula-fd
		  echo -e "label\nMyVolume\n2\nrun\n1\nyes\nmessages\nstatus director" | bconsole
		  


		  

		  
        SHELL
      end

      end
   end
end
