# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :testraid10 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 10000,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 10000, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 10000,
                        :port => 3
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "2048"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
		  
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
		  echo "Install required software"
	      yum install -y mdadm smartmontools hdparm gdisk
		  echo "Create partitions on disks /dev/sd[bc]"
		  echo -e "n\np\n1\n\n\nw" | fdisk /dev/sdb
		  echo -e "n\np\n1\n\n\nw" | fdisk /dev/sdc
		  echo "Create RAID 1 on /dev/sd[bcde]"
		  partprobe
		  mdadm --create --verbose /dev/md0 --level=1 --raid-devices=2 /dev/sd[bc]1
		  mdadm --detail /dev/md0
		  echo "Waiting Raid sync.."		  
		  sleep 30
		  mdadm --detail /dev/md0
		  parted /dev/md0 mklabel gpt
		  echo "Show current partitions"
		  parted /dev/md0 print

  	  SHELL
	  


      end
  end
end

