---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure HBAC Rule allhosts is disabled
    ipahbacrule:
      ipaadmin_password: MyPassword123
      name: allhosts
      state: disabled
