---      
    
    - name: Download nextcloud release
      get_url:
        url: "https://download.nextcloud.com/server/releases/{{ nextcloud_url }}"
        dest: /tmp/

    - name: Install unzip
      yum: pkg=unzip state=latest

    - name: unzip nextcloud archive
      shell: cd /tmp/ && unzip -o "/tmp/{{ nextcloud_url }}"

    - name: copy nextcloud files
      command: cp -rf /tmp/nextcloud /var/www/

    - name: create nextcloud data dir
      shell: mkdir "{{ datacloud }}" && chown -R nginx:nginx "{{ datacloud }}" 
      ignore_errors: True

    - name: Install semanage
      yum: pkg=policycoreutils-python state=latest

    - name: Add nextcloud nginx cofig
      template: src=nextcloud.conf dest=/etc/nginx/conf.d/nextcloud.conf

    - name: Add nextcloud cofig
      template: src=config.php dest=/var/www/nextcloud/config/config.php      

    - name: set permissions for  nextcloud files
      shell: chmod 755 /var/www/nextcloud && chown -R nginx:nginx /var/www/nextcloud

    - name: setup SElinux
      command: "{{ item }}"
      loop:
        - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/data(/.*)?'
        - semanage fcontext -a -t httpd_sys_rw_content_t '{{ datacloud }}(/.*)?'
        - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/config(/.*)?'
        - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/apps(/.*)?'
        - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/.htaccess'
        - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/.user.ini'
        - semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?'
        - restorecon -R '/var/www/nextcloud/'
        - setsebool -P httpd_can_network_connect on
      ignore_errors: True        



    - name: nginx restart
      service: name=nginx state=restarted


    - name: set permissions for  nextcloud files
      shell: cd /var/www/nextcloud && sudo -u nginx php occ  maintenance:install --database "pgsql" --database-name "{{ dbname }}"  --database-user "{{ dbuser }}" --database-pass "{{ dbpassword }}" --database-host "{{ dbhost }}" --admin-user "{{ nextcloud_user }}" --admin-pass "{{ nextcloud_user_pass }}" --data-dir "{{ datacloud }}" 