---
    - name: Add Nginx Repository
      copy: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root
      register: nginx_repo
      
    - name: Install Nginx
      yum: pkg=nginx state=latest
      when: nginx_repo is succeeded
      register: nginxinstalled
      notify:
          - nginx start
          
    - name: Enable Nginx Service
      service:
        name: nginx
        enabled: yes
      when: nginxinstalled is succeeded
      register: nginxenabled
      
    - name: install php72 repo
      command: yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
      
    - name: install php72 
      command: yum install -y php72 php72-php-fpm php72-php-gd php72-php-json php72-php-mbstring php72-php-mysqlnd php72-php-xml php72-php-xmlrpc php72-php-opcache
      
    - name: create php symlink
      command: ln -s /usr/bin/php72 /usr/bin/php

    - name: Add NGINX cofig
      when: nginxenabled is succeeded
      template: src=default.conf dest=/etc/nginx/conf.d/default.conf owner=nginx group=nginx

    - name: Copy custom page
      copy: src=index.html dest=/usr/share/nginx/html/index.html owner=nginx group=nginx
      register: nginx_page