---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  - name: Add group members sysops and appops to group sysops
    ipagroup:
      ipaadmin_password: MyPassword123
      name: ops
      group:
      - sysops
      - appops
