---
- name: Playbook to handle users
  hosts: ipaserver
  become: true

  tasks:
  - name: Enable user pinky
    ipauser:
      ipaadmin_password: MyPassword123
      name: pinky
      state: enabled
