---
    - name: Add Nginx Repository
      copy: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root
      register: nginx_repo
      
    - name: Install Nginx
      yum: pkg=nginx state=latest
      when: nginx_repo is succeeded
      register: nginxinstalled
      notify:
          - nginx start
          
    - name: Enable Nginx Service
      service:
        name: nginx
        enabled: yes
      when: nginxinstalled is succeeded
      register: nginxenabled

    - name: Add NGINX cofig
      when: nginxenabled is succeeded
      template: src=default.conf dest=/etc/nginx/conf.d/default.conf owner=nginx group=nginx

    - name: Copy custom page
      copy: src=index.html dest=/usr/share/nginx/html/index.html owner=nginx group=nginx
      register: nginx_page