---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - ipavault:
      ipaadmin_password: MyPassword123
      name: stdvault
      username: admin
      state: absent
