---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure host server is absent in Sudo Rule
  - ipasudorule:
      ipaadmin_password: MyPassword123
      name: testrule1
      host: server
      action: member
      state: absent
