---
- name: Tests
  hosts: ipaserver
  become: true

  tasks:
  # Ensure sudorule command is enabled
  - ipasudorule:
      ipaadmin_password: MyPassword123
      name: testrule1
      state: enabled
