---
- name: Host present with managedby_host
  hosts: ipaserver
  become: true

  tasks:
    ipahost:
      ipaadmin_password: MyPassword123
      name: host01.exmaple.com
      managedby_host: server.exmaple.com
      force: yes
